name: topwr_sci_clubs_form
description: "Ankieta dla kół i organizacji do aplikacji ToPWR, mobilnego
  przewodnika po Politechnice Wrocławskiej, zrobionego przez Koło Naukowe
  Solvro"
publish_to: "none"
version: 1.0.8+8

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  theme_tailor_annotation: ^3.0.1
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  enum_map: ^0.3.0
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  url_launcher: ^6.3.0
  envied: ^0.5.4+1
  graphql: ^5.1.3
  flutter_widget_from_html_core: ^0.15.1
  collection: ^1.18.0
  device_frame: ^1.2.0
  separate: ^1.0.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  reactive_image_picker: ^5.0.1
  dotted_border: ^2.1.0
  super_drag_and_drop: ^0.8.17
  file_picker: ^8.0.5
  reactive_segmented_control: ^2.0.1
  split_view: ^3.2.1
  reactive_forms_annotations: ^5.0.0
  reactive_forms:
    git: https://github.com/simon-the-shark/reactive_forms.git
  firebase_storage: ^12.1.0
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  logger: ^2.3.0
  firebase_auth: ^5.1.1
  http: ^1.2.1
  uuid: ^4.4.0
  scrollable_positioned_list: ^0.3.8
  pointer_interceptor: ^0.10.1+1
  auto_route: ^8.2.0
  flutter_inappwebview_web: ^1.0.8
  fleather: ^1.16.0
  parchment_delta: ^1.0.0
  parchment: ^1.15.0
  total_lints: ^3.4.0
  html: ^0.15.4
  path_provider: ^2.1.4
  fast_immutable_collections: ^10.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  riverpod_generator: ^2.4.2
  theme_tailor: ^3.0.1
  enum_map_gen: ^0.3.0
  riverpod_lint: ^2.3.12
  envied_generator: ^0.5.4+1
  graphql_codegen: ^0.14.0
  reactive_forms_generator: ^5.0.4
  freezed: ^2.5.3
  json_serializable: ^6.8.0
  auto_route_generator: ^8.0.0
  shared_preferences: ^2.2.3
  dart_firebase_admin: ^0.3.1

dependency_overrides:
  analyzer: ^6.5.0
  meta: ^1.15.0
  reactive_forms:
    git: https://github.com/simon-the-shark/reactive_forms.git
  lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/splash_screen/splash_logo.png
    - assets/logo_app_bar.svg
    - assets/created_by_vert.svg
    - assets/search_box/vectorsearch.svg
    - assets/undraw/injured.svg
    - assets/undraw/camping.svg
    - assets/undraw/landing.svg
    - assets/undraw/sent.svg
    - assets/preview.png
    - assets/contact_icons/compass.svg
    - assets/contact_icons/fb.svg
    - assets/contact_icons/github.svg
    - assets/contact_icons/ig.svg
    - assets/contact_icons/linkedin.svg
    - assets/contact_icons/mail.svg
    - assets/contact_icons/phone.svg
    - assets/contact_icons/web.svg
    - assets/contact_icons/yt.svg
    - assets/contact_icons/x.svg
    - assets/contact_icons/tiktok.svg
    - assets/contact_icons/discord.svg

  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/rubik/Rubik-Light.ttf
          weight: 300
        - asset: fonts/rubik/Rubik-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/rubik/Rubik-Regular.ttf
          weight: 400
        - asset: fonts/rubik/Rubik-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/rubik/Rubik-Medium.ttf
          weight: 500
        - asset: fonts/rubik/Rubik-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: fonts/rubik/Rubik-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/rubik/Rubik-Bold.ttf
          weight: 700
        - asset: fonts/rubik/Rubik-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/rubik/Rubik-ExtraBold.ttf
          weight: 800
        - asset: fonts/rubik/Rubik-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/rubik/Rubik-Black.ttf
          weight: 900
        - asset: fonts/rubik/Rubik-BlackItalic.ttf
          weight: 900
          style: italic
    - family: BottomNavBarIcon
      fonts:
        - asset: fonts/BottomNavBarIcon.ttf
    - family: IParkingIcons
      fonts:
        - asset: fonts/IParkingIcons.ttf
flutter_native_splash:
  background_image: assets/splash_screen/native_splash_bg.png
  image: assets/splash_screen/splash_logo.png

  android_12:
    color: "#EE6644"
    image: assets/splash_screen/splash_logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon.png"
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#EE6644"
    theme_color: "#EE6644"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
  macos:
    generate: true
    image_path: "assets/app_icon.png"
