name: Deploy

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Add envs
        run: cp .env.example .env

      - name: Add firebase config
        run: |
          echo "${{ secrets.FIREBASE_CONFIG }}" | base64 --decode > lib/firebase_options.dart

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/Solvro/web-topwr-sci-clubs-form:latest
          cache-from: type=registry,ref=ghcr.io/Solvro/web-topwr-sci-clubs-form:latest
          cache-to: type=inline
          network: host

      - name: Trigger build
        run: |
          curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
